### PR TITLE
Add detection and configuration for Enlightenment

### PR DESCRIPTION
**Pull request by hupfdule**
- Provide detection of running enlightenment instance
- Provide terminology and efm as default applications

### CODE REVIEW

**Comment by Chris2011** [comment]
Please change it to develop. Thx.

**Comment by hupfdule** [comment]
> Please change it to develop. Thx.

done

**Comment by hupfdule** [comment]
Well, it seems `develop` is several commits behind `master`…

**Comment by Chris2011** [comment]
Now it should be same. Forgot to merge.

**Pull request merged**
